### PR TITLE
detect CRLF too

### PR DESCRIPTION
**Pull request by kbomb**
Heyo, @timhudson !!! :smile:

### CODE REVIEW

**Comment by tonyghita** [comment]
Let's get this tested and into [finnp/detect-csv](https://github.com/finnp/detect-csv)!

**Comment by timhudson** [comment]
Unfortunately the `determineMost` logic only accounts for a single bit at a time so this change isn't enough to support CRLF.

**Comment by timhudson** [comment]
I'm closing this pull request since it should be submitted to finnp/detect-csv.

**Comment by kbomb** [comment]
Damn.

**Comment by kbomb** [comment]
But but it looked like it worked in my tests. T__T ARGH.

**Comment by tonyghita** [comment]
@kbomb I think you should submit to finnp/detect-csv with some tests when you get a change :)

**Pull request closed without merging**
